spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/satellite-tracker-db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always

spacetrack:
  identity: ${SPACETRACK_IDENTITY}
  password: ${SPACETRACK_PASSWORD}

sattrack:
  batch:
    leo:
      orbit-type: "LEO"
      epoch-window: "24h"
      exclude-decayed: true
      cleanup-threshold-days: 7
      chunk-size: 500
      cron: "0 0 */2 * * *"    # every 2 hours
      retry-delay-ms: 180000   # 3 minutes between retries
    meo:
      orbit-type: "MEO"
      epoch-window: "30d"
      exclude-decayed: true
      cleanup-threshold-days: 35
      chunk-size: 500
      cron: "0 0 0 * * *"      # daily at midnight
      retry-delay-ms: 180000
    heo:
      orbit-type: "HEO"
      epoch-window: "72h"
      exclude-decayed: true
      cleanup-threshold-days: 14
      chunk-size: 500
      cron: "0 0 */12 * * *"   # every 12 hours
      retry-delay-ms: 180000
    geo:
      orbit-type: ""
      epoch-window: "180d"
      exclude-decayed: true
      cleanup-threshold-days: 60
      chunk-size: 500
      cron: "0 0 0 * * SUN"    # weekly on Sunday
      retry-delay-ms: 180000
